import { MenuItem, Category } from "@/types/menu";

export const MOCK_CATEGORIES: Category[] = [
    { _id: "cat-1", title: "Kagi Signature", slug: "kagi-signature", icon: "🍜", order: 1 },
    { _id: "cat-2", title: "Spicy Series", slug: "kagi-spicy-series", icon: "🌶️", order: 2 },
    { _id: "cat-3", title: "Donburi", slug: "kagi-donburi", icon: "🍚", order: 3 },
    { _id: "cat-4", title: "Kids Menu", slug: "kids-menu", icon: "👶", order: 4 },
    { _id: "cat-5", title: "Small Dishes", slug: "small-dishes", icon: "🥟", order: 5 },
    { _id: "cat-6", title: "Additional", slug: "additional", icon: "➕", order: 6 },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
    // ===== KAGI SIGNATURE =====
    {
        _id: "sig-1",
        name: "Kuro Garikku",
        slug: "kuro-garikku",
        image: "/images/menu/kuro-garikku.jpg",
        price: 50000,
        description: "Ramen otentik dengan kuah kaldu sapi yang diperkaya intensitas black garlic, disajikan bersama topping paha ayam empuk dan telur ajitama meleleh.",
        category: "kagi-signature",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "sig-2",
        name: "Kagi Shoyu Saikoro",
        slug: "kagi-shoyu-saikoro",
        image: "/images/menu/shoyu-saikoro.jpg",
        price: 57500,
        description: "Ramen kuah kaldu sapi dengan shoyu special dan daging saikoro yang smoky dan juicy.",
        category: "kagi-signature",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "sig-3",
        name: "Beef Miruku",
        slug: "beef-miruku",
        image: "/images/menu/beef-miruku.jpg",
        price: 61250,
        description: "Ramen kuah creamy dengan kaldu kental berpadu smoke beef yang menggugah selera.",
        category: "kagi-signature",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "sig-4",
        name: "Saikoro Miruku",
        slug: "saikoro-miruku",
        image: "/images/menu/saikoro-miruku.jpg",
        price: 57500,
        description: "Ramen kuah creamy gurih dengan potongan saikoro yang smoky dan juicy.",
        category: "kagi-signature",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "sig-5",
        name: "Kagi Toripaitan",
        slug: "kagi-toripaitan",
        image: "/images/menu/toripaitan.jpg",
        price: 47500,
        description: "Mahakarya klasik: Ramen kuah kaldu ayam kental yang diekstraksi perlahan, dilengkapi paha ayam panggang dan ajitama sempurna.",
        category: "kagi-signature",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "sig-6",
        name: "Kagi Shoyu Beef",
        slug: "kagi-shoyu-beef",
        image: "/images/menu/shoyu-beef.jpg",
        price: 61250,
        description: "Ramen kuah kaldu sapi dengan shoyu special dan smoked beef premium.",
        category: "kagi-signature",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "sig-7",
        name: "Chizu Beef",
        slug: "chizu-beef",
        image: "/images/menu/chizu-beef.jpg",
        price: 57500,
        description: "Ramen kuah keju special yang gurih creamy dengan smoked beef pilihan.",
        category: "kagi-signature",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "sig-8",
        name: "Truffle Dry Ramen",
        slug: "truffle-dry-ramen",
        image: "/images/menu/truffle-dry.jpg",
        price: 72500,
        description: "The fusion of European and Japanese flavours. Premium truffle oil dengan mi khas Kagi.",
        category: "kagi-signature",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "sig-9",
        name: "Chizu Saikoro",
        slug: "chizu-saikoro",
        image: "/images/menu/chizu-saikoro.jpg",
        price: 55000,
        description: "Ramen dengan kuah keju special yang gurih creamy dilengkapi potongan daging saikoro.",
        category: "kagi-signature",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "sig-10",
        name: "Tori Gekikara",
        slug: "tori-gekikara",
        image: "/images/menu/tori-gekikara.jpg",
        price: 45000,
        description: "Dry ramen berbalut saus rahasia manis-gurih, disajikan dengan paha ayam panggang empuk beraroma asap.",
        category: "kagi-signature",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "sig-11",
        name: "Saikoro Gekikara",
        slug: "saikoro-gekikara",
        image: "/images/menu/saikoro-gekikara.jpg",
        price: 50000,
        description: "Dry ramen diaduk dengan saus Jepang autentik manis-gurih, ditaburi potongan saikoro panggang yang juicy.",
        category: "kagi-signature",
        isPopular: false,
        isUpsell: false,
    },

    // ===== KAGI SPICY SERIES =====
    {
        _id: "spy-1",
        name: "Spicy Toripaitan",
        slug: "spicy-toripaitan",
        image: "/images/menu/spicy-toripaitan.jpg",
        price: 52500,
        description: "Ramen kuah kaldu ayam kental pedas-gurih yang meresap sempurna pada mi, dilengkapi paha ayam dan ajitama.",
        category: "kagi-spicy-series",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "spy-2",
        name: "Saikoro Miruku Spicy",
        slug: "saikoro-miruku-spicy",
        image: "/images/menu/saikoro-miruku-spicy.jpg",
        price: 67500,
        description: "Kuah creamy kental yang membelai lidah, dipadukan dengan racikan cabai khas Kagi dan daging saikoro smoky.",
        category: "kagi-spicy-series",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "spy-3",
        name: "Chizu Beef Spicy",
        slug: "chizu-beef-spicy",
        image: "/images/menu/chizu-beef-spicy.jpg",
        price: 65000,
        description: "Harmoni kuah keju gurih yang sangat lembut, berpadu dengan sensasi pedas dan keharuman smoked beef.",
        category: "kagi-spicy-series",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "spy-4",
        name: "Chizu Saikoro Spicy",
        slug: "chizu-saikoro-spicy",
        image: "/images/menu/chizu-saikoro-spicy.jpg",
        price: 67500,
        description: "Kuah keju gurih berpadu dengan sengatan cabai khas Kagi, disempurnakan oleh potongan saikoro juicy.",
        category: "kagi-spicy-series",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "spy-5",
        name: "Beef Miruku Spicy",
        slug: "beef-miruku-spicy",
        image: "/images/menu/beef-miruku-spicy.jpg",
        price: 65000,
        description: "Ramen kuah creamy kental bercampur cabe racikan khas Kagi dengan smoked beef premium.",
        category: "kagi-spicy-series",
        isPopular: false,
        isUpsell: false,
    },

    // ===== KAGI DONBURI =====
    {
        _id: "don-1",
        name: "Beef Teriyaki Don",
        slug: "beef-teriyaki-don",
        image: "/images/menu/beef-teriyaki-don.jpg",
        price: 50000,
        description: "Nasi hangat berpadu dengan irisan daging sapi teriyaki premium dan kelembutan scramble egg.",
        category: "kagi-donburi",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "don-2",
        name: "Chicken Teriyaki Don",
        slug: "chicken-teriyaki-don",
        image: "/images/menu/chicken-teriyaki-don.jpg",
        price: 43750,
        description: "Nasi hangat disajikan dengan potongan ayam saus teriyaki yang kaya rasa dan scramble egg.",
        category: "kagi-donburi",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "don-3",
        name: "Nanban Chicken Donburi",
        slug: "nanban-chicken-donburi",
        image: "/images/menu/nanban-chicken.jpg",
        price: 43750,
        description: "Nasi hangat dengan tekstur ayam krispi dibalut saus pedas manis Nanban yang segar, ditemani scramble egg.",
        category: "kagi-donburi",
        isPopular: false,
        isUpsell: false,
    },

    // ===== KIDS MENU =====
    {
        _id: "kid-1",
        name: "Yakiniku Bento",
        slug: "yakiniku-bento",
        image: "/images/menu/yakiniku-bento.jpg",
        price: 40000,
        description: "Sajian bento porsi anak dengan beef slice bumbu yakiniku manis, dilengkapi scramble egg dan salad.",
        category: "kids-menu",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "kid-2",
        name: "Katsu Bento",
        slug: "katsu-bento",
        image: "/images/menu/katsu-bento.jpg",
        price: 30000,
        description: "Sajian bento dengan nasi porsi anak, chicken katsu krispi di luar lembut di dalam, scramble egg, dan salad.",
        category: "kids-menu",
        isPopular: true,
        isUpsell: false,
    },
    {
        _id: "kid-3",
        name: "Toripop Bento",
        slug: "toripop-bento",
        image: "/images/menu/toripop-bento.jpg",
        price: 30000,
        description: "Sajian bento anak dengan ayam popcorn gurih manis, dilengkapi nasi dan salad segar.",
        category: "kids-menu",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "kid-4",
        name: "Kochizu Ramen",
        slug: "kochizu-ramen",
        image: "/images/menu/kochizu-ramen.jpg",
        price: 36250,
        description: "Ramen porsi anak dengan kuah keju yang gurih dan creamy, favorit si kecil!",
        category: "kids-menu",
        isPopular: false,
        isUpsell: false,
    },
    {
        _id: "kid-5",
        name: "Minitori Ramen",
        slug: "minitori-ramen",
        image: "/images/menu/minitori-ramen.jpg",
        price: 31250,
        description: "Ramen porsi anak dengan kuah toripaitan yang gurih dan kental, lembut di lidah.",
        category: "kids-menu",
        isPopular: false,
        isUpsell: false,
    },

    // ===== SMALL DISHES =====
    {
        _id: "sd-1",
        name: "Chicken Karaage",
        slug: "chicken-karaage",
        image: "/images/menu/karaage.jpg",
        price: 31250,
        description: "Potongan ayam goreng ala Jepang yang juicy dan super crispy.",
        category: "small-dishes",
        isPopular: true,
        isUpsell: true,
    },
    {
        _id: "sd-2",
        name: "Karaage Mentai",
        slug: "karaage-mentai",
        image: "/images/menu/karaage-mentai.jpg",
        price: 35000,
        description: "Ayam goreng juicy dan crispy dengan siraman saus mentai gurih leleh yang menggugah selera.",
        category: "small-dishes",
        isPopular: true,
        isUpsell: true,
    },
    {
        _id: "sd-3",
        name: "Gyoza",
        slug: "gyoza",
        image: "/images/menu/gyoza.jpg",
        price: 35000,
        description: "Pangsit ala Jepang dengan isian daging ayam juicy yang di-steam sempurna.",
        category: "small-dishes",
        isPopular: true,
        isUpsell: true,
    },
    {
        _id: "sd-4",
        name: "Kimchi Gyoza",
        slug: "kimchi-gyoza",
        image: "/images/menu/kimchi-gyoza.jpg",
        price: 40000,
        description: "Pangsit ala Jepang dengan isian daging ayam dipadukan dengan tendangan kimchi pedas-gurih.",
        category: "small-dishes",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "sd-5",
        name: "Yakitori",
        slug: "yakitori",
        image: "/images/menu/yakitori.jpg",
        price: 37500,
        description: "Sate paha ayam otentik yang dipanggang sempurna dengan lumuran bumbu yakiniku.",
        category: "small-dishes",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "sd-6",
        name: "Tamagoyaki",
        slug: "tamagoyaki",
        image: "/images/menu/tamagoyaki.jpg",
        price: 25000,
        description: "Telur gulung tebal tradisional Jepang bertekstur lembut dengan rasa gurih manis.",
        category: "small-dishes",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "sd-7",
        name: "Kentang Sosis",
        slug: "kentang-sosis",
        image: "/images/menu/kentang-sosis.jpg",
        price: 25000,
        description: "Kentang goreng renyah yang dilengkapi dengan sosis goreng, cocok untuk berbagi.",
        category: "small-dishes",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "sd-8",
        name: "Tomoro Koshi",
        slug: "tomoro-koshi",
        image: "/images/menu/tomoro-koshi.jpg",
        price: 25000,
        description: "Jagung manis bakar yang dikaramelisasi dengan saus spesial dan lumuran saus mentai.",
        category: "small-dishes",
        isPopular: false,
        isUpsell: true,
    },

    // ===== ADDITIONAL TOPPINGS =====
    {
        _id: "add-1",
        name: "Topping Paha Ayam",
        slug: "topping-paha-ayam",
        image: "/images/menu/topping-ayam.jpg",
        price: 18750,
        description: "Seporsi topping paha ayam juicy untuk melengkapi ramen favoritmu.",
        category: "additional",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "add-2",
        name: "Beef Slice",
        slug: "beef-slice",
        image: "/images/menu/beef-slice.jpg",
        price: 31250,
        description: "Seporsi smoked beef premium berkualitas tinggi.",
        category: "additional",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "add-3",
        name: "Noodles Kagi",
        slug: "noodles-kagi",
        image: "/images/menu/noodles-kagi.jpg",
        price: 8750,
        description: "Seporsi mie tanpa kuah, perfect untuk tambahan porsi.",
        category: "additional",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "add-4",
        name: "Saikoro",
        slug: "saikoro-extra",
        image: "/images/menu/saikoro-extra.jpg",
        price: 31250,
        description: "Seporsi saikoro juicy yang smoky dan menggugah selera.",
        category: "additional",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "add-5",
        name: "Mini Katsu",
        slug: "mini-katsu",
        image: "/images/menu/mini-katsu.jpg",
        price: 12500,
        description: "Potongan ayam crispy ukuran mini yang gurih dan renyah di setiap gigitan.",
        category: "additional",
        isPopular: false,
        isUpsell: true,
    },
    {
        _id: "add-6",
        name: "Ajitama",
        slug: "ajitama",
        image: "/images/menu/ajitama.jpg",
        price: 10000,
        description: "Sebutir telur yang sudah dimarinasi, kuning meleleh sempurna.",
        category: "additional",
        isPopular: false,
        isUpsell: true,
    },
];
